Repository cybergis/cybergis-compute-python-sdk, pull requests merged in 2022-09, with the labels that each got.

#49 Cleaned Up Repo and Released on PyPi
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  RIF_UI_NBK/Demo Notebook New Process.ipynb
  RIF_UI_NBK/Demo Notebool Old Process.ipynb
  RIF_UI_NBK/iPython Widget.ipynb
  docs/models.rst
  docs/reference.rst
  docs/release-notes.rst
  example_output/.file_config.json
  example_output/job.stderr
  example_output/job.stdout
  hello_world.ipynb
  setup.cfg
  setup.py
  spatial_accessibility.ipynb
Labels: documentation, new feature

#51 should fix list_job() (issue #50)
  cybergis_compute_client/CyberGISCompute.py
Labels: bug fix

#55 Whitelist
  cybergis_compute_client/CyberGISCompute.py
Labels: enhancement

#57 hoping to solve --force-reinstall errors
  setup.py
Labels: bug fix
